import "./globals.css";
import type { Metadata } from "next";
import { Inter, Exo_2, JetBrains_Mono } from "next/font/google";
import { ChatBot } from "@/components/ui/ChatBot";
import {
  getSiteBrand,
  getCompanyContact,
  getSocialLinks,
} from "@/lib/site-settings";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans-import", display: "swap" });
const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800", "900"],
  variable: "--font-display-import",
  display: "swap",
});
const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono-import",
  display: "swap",
});

const SITE_URL = "https://www.tertiaryinfotech.edu.sg";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Advanced Certificate Courses in AI, Cyber Security & Blockchain in Singapore | Tertiary Infotech Academy",
    template: "%s | Tertiary Infotech Academy",
  },
  description:
    "Study Advanced Certificate courses in AI, Cyber Security and Blockchain at Tertiary Infotech Academy — a Singapore Private Education Institution. Industry-recognised, hands-on certifications for international students and career switchers.",
  keywords:
    "advanced certificate Singapore, cyber security course Singapore, AI course Singapore, blockchain course Singapore, study cyber security in Singapore, study AI in Singapore, international students Singapore, CompTIA certification Singapore, Private Education Institution Singapore, Tertiary Infotech Academy",
  openGraph: {
    type: "website",
    siteName: "Tertiary Infotech Academy",
    locale: "en_SG",
    url: SITE_URL,
    // Branded 1200×630 card generated by src/app/opengraph-image.tsx.
    // Inherited by every route that doesn't set its own openGraph.images.
    images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Tertiary Infotech Academy — Advanced Certificate courses in AI, Cyber Security & Blockchain in Singapore" }],
  },
  twitter: { card: "summary_large_image", images: ["/opengraph-image"] },
  robots: { index: true, follow: true },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [brand, contact, socials] = await Promise.all([
    getSiteBrand().catch(() => null),
    getCompanyContact().catch(() => null),
    getSocialLinks().catch(() => []),
  ]);

  const orgLd = {
    "@context": "https://schema.org",
    "@type": "EducationalOrganization",
    name: brand?.fullName ?? "Tertiary Infotech Academy Pte Ltd",
    alternateName: brand?.shortName ?? "Tertiary Infotech Academy",
    description:
      "Singapore Private Education Institution offering Advanced Certificate courses in AI, Cyber Security and Blockchain for international students and career switchers.",
    url: SITE_URL,
    logo: brand?.logoUrl ? new URL(brand.logoUrl, SITE_URL).toString() : `${SITE_URL}/favicon.ico`,
    email: contact?.email,
    telephone: contact?.tel,
    address: contact?.address
      ? {
          "@type": "PostalAddress",
          streetAddress: contact.address,
          addressCountry: "SG",
        }
      : undefined,
    areaServed: "Worldwide",
    knowsAbout: ["Artificial Intelligence", "Cyber Security", "Blockchain", "CompTIA Certification"],
    sameAs: socials.map((s) => s.href),
    taxID: brand?.uen ?? undefined,
  };

  const websiteLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: brand?.shortName ?? "Tertiary Infotech Academy",
    url: SITE_URL,
    inLanguage: "en-SG",
    publisher: { "@type": "Organization", name: brand?.fullName ?? "Tertiary Infotech Academy Pte Ltd" },
    potentialAction: {
      "@type": "SearchAction",
      target: `${SITE_URL}/blog?tag={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };

  return (
    <html lang="en-SG" data-theme="dark" className={`${inter.variable} ${exo2.variable} ${mono.variable}`}>
      <body className="min-h-screen antialiased">
        {children}
        <ChatBot />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteLd) }}
        />
      </body>
    </html>
  );
}
